BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script: |
    bundle install
    bundle exec rake

# runtime_script: bundle exec rake package:$TR_PLATFORM:$TR_ARCH
# package_script: bundle exec rb2exe pact-broker-app.rb --target=$TARGET --daemon
# test_script: | # NOTE:- Cirrus CI/CLI Executors run in seperate shell sessions per test so the app is closed
#   ./pact-broker-app ../ruby/config.ru -P ~/pact_broker.pid
#   wget -qO- https://raw.githubusercontent.com/eficode/wait-for/4df3f9262d84cab0039c07bf861045fbb3c20ab7/wait-for | sh -s -- localhost:9292 -- echo "pact broker is up"
#   curl -v http://localhost:9292
#   cat ~/pact_broker.pid | xargs kill

macos_arm_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: oa64
    TR_PLATFORM: osx
    TR_ARCH: arm64
  cirrus_cli_script: |
    chmod +x bin/*
  << : *BUILD_TEST_TASK_TEMPLATE
  # binary_artifacts:
  #   path: "pkg/*"

# macos_x64_task: 
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-ventura-base:latest
#   ruby_version_script: ruby --version
#   env:
#     TARGET: ox64
#     USE_ROSETTA: arch -x86_64
#   cirrus_cli_script: |
#     chmod +x bin/*
#   rosetta_script: softwareupdate --install-rosetta --agree-to-license
#   << : *BUILD_TEST_TASK_TEMPLATE
#   binary_artifacts:
#     path: "pkg/*"

linux_arm_task: 
  env:
    TARGET: la64
    TR_PLATFORM: linux
    TR_ARCH: arm64
  arm_container:
    image: ruby:3.1
    cpu: 1
    memory: 1G
  pre_req_script: apt update --yes && apt install -y build-essential squashfs-tools automake libtool
  # pre_req_script: apt update --yes && apt install --yes git zip curl wget netcat-traditional
  # bundler_setup_script: |
  #     bundle install
  << : *BUILD_TEST_TASK_TEMPLATE

# linux_amd_task: 
#   env:
#     TARGET: lx64
#   container:
#     image: ruby:3.2.2-slim
#     cpu: 1
#     memory: 1G
#   pre_req_script: apt update --yes && apt install --yes git zip curl wget netcat-traditional
#   ruby_setup_script: gem install bundler -v 2.4.18
#   << : *BUILD_TEST_TASK_TEMPLATE