macos_arm_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    BISON_PATH: "/opt/homebrew/opt/bison/bin"
    OPENSSL_1_1_PATH: "/opt/homebrew/opt/openssl@1.1/lib"
    PATH: "$BISON_PATH:$PATH"
  cirrus_cli_script: |
    chmod +x bin/*
    find . -name '*onfigure' -type f | xargs chmod +x
    find . -name '*.sh' -type f | xargs chmod +x
    find .  -name 'install-sh' -type f | xargs chmod +x
    brew install automake texinfo libtool squashfs bison
    bin/rubyc bin/rubyc -o rubyc
    DYLD_LIBRARY_PATH=/opt/homebrew/opt/openssl@1.1/lib rubyc --help
    mkdir pkg
    mv rubyc pkg/rubyc-darwin-arm64
  # << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

task:
  arm_container:
    matrix:
      - dockerfile: Dockerfile
        docker_arguments:
          - matrix:
              - ARCH: arm64
              - ARCH: x86_64
  binary_artifacts:
    path: "rubyc"