AllCops:
  NewCops: enable
  Exclude:
    - ruby/**/*
    - ruby-/**/*
    - vendor/**/*
    - vendor-enclose/**/*
    - ruby-enclose/**/*
    - ruby-enclose-*/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false
