name: Linux
on:
  push:
    branches: [ master, ci_test  ]
  pull_request:
    branches: [ master, ci_test  ]
  workflow_dispatch:
jobs:
  make:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.2']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: "[Enclose.IO] Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y build-essential squashfs-tools automake libtool bison
      - uses: actions/checkout@v3
      - name: "[Enclose.IO] Check dependencies"
        run: |
          cat /etc/issue
          uname -a
          uname -p
          uname -m
          lscpu
          which mksquashfs
          mksquashfs -version
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: "[Enclose.IO] Install rubocop"
        run: gem install rubocop
      - name: "[Enclose.IO] Run rubocop"
        run: rubocop
      - name: "[Enclose.IO] Bundle install"
        run: bundle install
      - name: "[Enclose.IO] Rake"
        run: bundle exec rake
      - name: "[Enclose.IO] Create Linux Test run upload"
        uses: actions/upload-artifact@v3
        with:
          name: rubyc-${{ matrix.os }}
          path: ./rubyc
