name: macOS
on:
  push:
    branches: [ master, ci  ]
  pull_request:
    branches: [ master, ci  ]
  workflow_dispatch:
jobs:
  make:
    strategy:
      matrix:
        os: [macos-latest]
        # ruby: ['2.4','2.6','2.7', '3.0', '3.1', '3.2']
        ruby: ['3.1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "[Enclose.IO] Install dependencies"
        run: |
          brew upgrade
          brew install squashfs automake
      - name: "[Enclose.IO] Check dependencies"
        run: |
          sw_vers
          uname -a
          uname -p
          uname -m
          sysctl -n machdep.cpu.brand_string
          which mksquashfs
          mksquashfs -version
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: "[Enclose.IO] Install rubocop"
        run: gem install rubocop
      # - name: "[Enclose.IO] Run rubocop"
      #   run: rubocop
      - name: "[Enclose.IO] Install dependencies"
        run: bundle install
      - name: "[Enclose.IO] Rake"
        run: bundle exec rake
      # - name: "[Enclose.IO] Create macOS Release"
      #   if: ${{ github.ref == 'refs/heads/master' && success() }}
      #   id: create_macos_release
      #   uses: pmq20/create-release@delete-old-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: darwin-x64
      #     release_name: Latest macOS Pre-release
      #     draft: false
      #     prerelease: true
      #     replace_old_tag: true
      # - name: "[Enclose.IO] Upload macOS Release"
      #   if: ${{ github.ref == 'refs/heads/master' && success() }}
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_macos_release.outputs.upload_url }}
      #     asset_path: ./rubyc
      #     asset_name: rubyc
      #     asset_content_type: application/octet-stream
