name: macOS
on:
  push:
    branches: [ master, ci_test  ]
  pull_request:
    branches: [ master, ci_test  ]
  workflow_dispatch:
jobs:
  make:
    strategy:
      matrix:
        os: [macos-latest]
        # ruby: ['2.4','2.6','2.7', '3.0', '3.1', '3.2']
        ruby: ['3.2']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "[Enclose.IO] Install dependencies"
        run: |
          brew upgrade
          brew install squashfs automake bison
          brew info bison
          echo "PATH=$(brew --prefix bison)/bin:$PATH" >>$GITHUB_ENV
      - name: "[Enclose.IO] Check dependencies"
        run: |
          sw_vers
          uname -a
          uname -p
          uname -m
          sysctl -n machdep.cpu.brand_string
          which mksquashfs
          mksquashfs -version
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: "[Enclose.IO] Install rubocop"
        run: gem install rubocop
      - name: "[Enclose.IO] Run rubocop"
        run: rubocop
      # - name: "[Enclose.IO] Install dependencies"
      #   run: bundle install
      # - name: "[Enclose.IO] Rake"
      #   run: bundle exec rake
      - name: "Package rubyc"
        run: bin/rubyc bin/rubyc -o rubyc
      - name: "[Enclose.IO] Create MacOS Test run upload"
        uses: actions/upload-artifact@v3
        with:
          name: rubyc-${{ runner.os }}
          path: ./rubyc
