name: Windows
on:
  push:
    branches: [ master, ci_test ]
  pull_request:
    branches: [ master, ci_test ]
  workflow_dispatch:
jobs:
  make:
    strategy:
      matrix:
        # ruby: ['2.4','2.6','2.7', '3.0', '3.1', '3.2']
        ruby: ['3.2']
        vs: [2019]
        # include:
        #   - os: windows-2019
        #     vs: 2019
      fail-fast: false
    runs-on: windows-2019
    env:
      ENCLOSE_IO_RUBYC_ADDTIONAL_ARGS: --tmpdir=C:\rubyc_tmp
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name: "[Enclose.IO] Install libraries"
        run: |
          choco install --no-progress squashfs
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: "[Enclose.IO] Install rubocop"
        run: gem install rubocop
      - name: "[Enclose.IO] Run rubocop"
        run: rubocop
      - name: "[Enclose.IO] Install dependencies"
        run: bundle install
      # - name: "[Enclose.IO] Set up Perl"
      #   run: |
      #     choco install strawberryperl
      #     echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: "[Enclose.IO] Inspect Windows Environment"
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo on
          wmic OS get OSArchitecture
          echo %PROCESSOR_ARCHITECTURE%
          set
          systeminfo
          where perl
          perl -V
          where nmake
          where mksquashfs
          mksquashfs -version
          where ruby
          ruby -v
          where bundle
          bundle -v
        shell: cmd
      # - name: "[Enclose.IO] Rake"
      #   run: |
      #     call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      #     mkdir C:\rubyc_tmp
      #     bundle exec rake
      #   shell: cmd
      - name: "Package rubyc"
        run: bin/rubyc bin/rubyc -o rubyc
      - name: "Package rubyc"
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          mkdir C:\rubyc_tmp
          bin/rubyc.bat bin/rubyc -o rubyc.exe
        shell: cmd
      - name: "[Enclose.IO] Create Windows Test run upload"
        uses: actions/upload-artifact@v3
        with:
          name: rubyc-${{ runner.os }}
          path: ./rubyc
